version: "3.4"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: nymlog
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nymlog
    volumes:
      - mongo-data:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    networks:
      - nymlognet
  nymlog:
    image: nymlog
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      NODE_ENV: production
      MONGO_DB: nymlog
      MONGO_USERNAME: root
      MONGO_PASSWORD: nymlog
    volumes:
      - ./:/home/node/app
    ports:
      - 443:4000
    command: "npm run start"
    networks:
      - nymlognet
  vue-nymlog:
    image: vue-nymlog
    environment:
      NODE_ENV: production
    ports:
      - 4001:4001
    networks:
      - nymlognet
networks:
  nymlognet:
volumes:
  mongo-data:
