version: '3.4'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nymlog
    volumes:
      - db-data:/etc/mongo
    ports:
      - 27017:27017
    networks:
      - nymlognet
  nymlog:
    image: node:10-alpine
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    command: "npm start"
    networks:
      - nymlognet
networks:
  nymlognet:
volumes:
  db-data: