version: '3.4'
services:
  nymlog:
    image: nurielmeni/nymlog
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./:/node/nymlog
    networks:
      - nymlognet
networks:
  nymlognet: