version: '3.4'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nymlog
    volumes:
      - db-data:/etc/mongo
    networks:
      - nymlognet
  nymlog:
    image: nurielmeni/nymlog
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./:/node/nymlog
    networks:
      - nymlognet
networks:
  nymlognet:
volumes:
  db-data: